apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: teste-app-2
build:
  artifacts:
    - image: poc-backstage-sq/teste-app-2
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}